### ISSUE TITLE
Converting stroke svg to font

### ISSUE THREAD

**Issue by Dmitry31** [fontello/svg2ttf#104]
By chance is there a way to convert a stroke based svg to a font icon? For exemple a cross that is composed of to lines like follows? Or It should always be the outline of the lines?
I tried preprocessing the input SVGs using outline-stroke-cli, but the resulting SVGs have weird shape.

<svg viewBox="0 0 140 140" height="140" width="140" xmlns="http://www.w3.org/2000/svg">
  <g transform="matrix(5.833333333333333,0,0,5.833333333333333,0,0)">
    <path d="M0.5 0.499L23.5 23.499" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round"></path>
    <path d="M23.5 0.499L0.5 23.499" fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round"></path>
  </g>
</svg>

**Comment by puzrin** [comment]
Input images MUST be outlines. Try to prepare in inskape or something else https://github.com/fontello/fontello/wiki/How-to-use-custom-images
