### ISSUE TITLE
Change the OS/2 table version to 4

### ISSUE THREAD

**Issue by yisibl** [fontello/svg2ttf#106]
We have enabled fsSelection bit 7, which was added in version 4.

> Bit 7 was defined in version 4. For new fonts, vendors are encouraged to use a version 4 or later OS/2 table and to have bit 7 set.
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#:~:text=bit%207%3A

**Comment by puzrin** [comment]
Fixed by https://github.com/fontello/svg2ttf/commit/118e7b74b87dd8b65e6cfa2060563f49872f00cd
