### ISSUE TITLE
Unable to use multiple dots in version

### ISSUE THREAD

**Issue by misolori** [fontello/svg2ttf#114]
when using the version option, using `1.0.0` will not count as a valid version but `1.0` will pass. 

```log
svg2ttf: invalid option, version - "1.0.0"
```

Given that node packages all use multiple dot versions, I would like to ask to support this. I currently use my package.json version as a string for this option and it fails.

**Comment by puzrin** [comment]
Fonts are NOT node packages. Also see #112 and continue there if you have "trusted" technical details to add.
