### ISSUE TITLE
Auditing webfont v11.2.20 which uses svg2ttf v6.02 reveals a moderate vulnerability in xmldom

### ISSUE THREAD

**Issue by PrashantChittiZS** [fontello/svg2ttf#115]
Running `npm audit` while using webfont v11.2.20, reveals a vulnerability in xmldom, which is internally used by `svg2ttf` v6.0.2. The vulnerability is moderate in severity and is said to be fixed in v0.7.0 of `xmldom`.

Here is the screenshot for reference:
![image](https://user-images.githubusercontent.com/88488118/128674482-40b08a9b-0625-47f5-adbd-ec221017a282.png)

**Comment by puzrin** [comment]
Nobody cares.
