### ISSUE TITLE
Can't find <font> tag. Make sure you SVG file is font, not image

### ISSUE THREAD

**Issue by LikeDreamwalker** [fontello/svg2ttf#121]
I am kind of confused. Am I missing something or just svg2ttf can only make svg(fonts) to ttf. I thought svg2ttf can make svg(icons) to ttf directly. Is there any other work  in this situation before I get started?

**Comment by LikeDreamwalker** [comment]
![1](https://user-images.githubusercontent.com/45194556/176637016-63ac9363-d052-495f-9b4e-8582a65ce8a9.svg)

**Comment by puzrin** [comment]
This package converts svg fonts, not standalone svg images. If you wish to pack images - there should be more high-level utilities, but I can't tell you an actual one.
