### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received an instance of Uint8Array

### ISSUE THREAD

**Issue by wmixx** [fontello/svg2ttf#122]
node:internal/validators:124
    throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "size" argument must be of type number. Received an instance of Uint8Array

**Comment by wmixx** [comment]
Is this error a node version problem?

**Comment by puzrin** [comment]
It's impossible to understand what happens with the existing info. Need minimalistic sample, how to reproduce, to reopen.

Note that this package has working tests: https://github.com/fontello/svg2ttf/blob/master/test/test.js. Maybe playing with those can help.
