### ISSUE TITLE
Add support for hkern and vkern elements.

### ISSUE THREAD

**Issue by michaelrhodes** [fontello/svg2ttf#16]
Obviously mostly useful for traditional typefaces, but I think even for icon fonts would benefit from this feature being supported.

**Example**

![without-kerning-pairs](https://f.cloud.github.com/assets/771995/2116446/3c377d66-9083-11e3-8b33-2ec9be5b9d98.png)
_Without kerning pairs_

![with-kerning-pairs](https://f.cloud.github.com/assets/771995/2116445/3c356846-9083-11e3-9e63-1e0792c2539a.png)
_With kerning pairs_

``` xml
<hkern g1="diamond" g2="diamond" k="100" />
<hkern g1="home" g2="home" k="-100" />
```

**Comment by puzrin** [comment]
This stays open too long, and seems nobody plan to participate. Let's close. This can be reopened anytime if someone wish to implement.
