### ISSUE TITLE
TTFs do not appear in the latest version of Keynote

### ISSUE THREAD

**Issue by cameronmcefee** [fontello/svg2ttf#20]
I'm currently working on trying to figure this out myself, but I figured I'd make an issue here in case you know the cause of the issue. In the latest version of Keynote, icon fonts generated with svg2ttf do not appear in the font list. They do appear in the native list, and icons will work in keynote if copied in, or if they already exist in the document.

From my debugging so far, it doesn't appear to be an issue with the name table, as copying the name table from a font that does work (with the info correctly updated) does not fix the issue.

When I run the generated icon font through the Windows ttf validator, it throws all kinds of errors, so it's possible something unrelated in the font is causing the problem.

**Comment by rtomayko** [comment]
> I finally figured out the issue. It's not a svg2ttf problem. Keynote's font list is a font-preview list, that is it prints the font's name using the font. Since icon fonts don't generally contain latin characters, Keynote would fail when looking for the necessary glyphs to preview, and would just omit the font from the list.

> I'm not currently sure what the best strategy is to resolve the issue, but that's not really relevant for this repo.

Just ran into this same issue trying to use an icon font in Keynote and figured I'd leave the workaround I found for future searchers that land here. If you use the *Format -> Font -> Show Fonts* palette instead of the Text inspector, fonts w/ non-latin characters show up fine:

![image](https://cloud.githubusercontent.com/assets/404/6152167/00ccb16e-b1e9-11e4-9a6b-4c0ac648c23f.png)

**Comment by cameronmcefee** [comment]
To follow up, what I've done for https://octicons.github.com/ is map latin characters (a-zA-Z) to GitHub's logo. That way there is something to render when the font is displayed in the list. It's a little weird and isn't readable (per se) but it does the trick to at least get it in the list.

![screen shot 2015-03-16 at 2 55 37 pm](https://cloud.githubusercontent.com/assets/72919/6677381/a9046f12-cbec-11e4-9348-6f59655e1ce2.png)
