### ISSUE TITLE
Conversion alters shapes

### ISSUE THREAD

**Issue by cameronmcefee** [fontello/svg2ttf#24]
Given the source:

![screen shot 2014-06-16 at 6 42 59 pm](https://cloud.githubusercontent.com/assets/72919/3295459/c4c4c22c-f5c0-11e3-9f17-83430a4b9c61.png)

The result is this:

![screen shot 2014-06-16 at 6 40 44 pm](https://cloud.githubusercontent.com/assets/72919/3295462/cc0a8c56-f5c0-11e3-80af-044c56e07529.png)

The issue appears to happen when converting from svg font -> ttf. I tested this by switching the font-face declaration to only use the svg font, which looks great.

I don't notice this issue in Fontello icons (which I presume use this lib), so I'm not sure why I'm experiencing this. 

Reference:
https://github.com/github/octicons/blob/master/svg/link.svg
http://octicons.github.com/icon/link/

**Comment by puzrin** [comment]
@cameronmcefee FYI, after ages... fixed :)

**Comment by cameronmcefee** [comment]
:tada: Awesome!
