### ISSUE TITLE
Problem with vertical-alignment.

### ISSUE THREAD

**Issue by maranomynet** [fontello/svg2ttf#26]
Hi. I've been having issues with vertical-alignment (both cross-browser, and compared with professional icon-font generators) in icon fonts generated using the [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont) module.

See discussion and screen-shots here:
https://github.com/nfroidure/gulp-iconfont/issues/13#issuecomment-47081644

According to the author of gulp-iconfont, a part of the problem may lie within svg2ttf module, which is why he asked me to submit this there also.

Here are example files and visual test-cases that I made, which may help track this down: http://mar.eplica.is/gulp-iconfont-tests.zip

**Comment by thamagnetix** [comment]
I'm having the same issue using the gulp-iconfont 1.0.1. (first asked there https://github.com/nfroidure/gulp-iconfont/issues/13) 

The svg2ttf and then ttf2woff, ends up causing the .woff to have a different vertical baseline in IE. To make sure it was the svg2ttf that was the problem i compared with the generated font from Iconmoon. Then I used the .ttf generated from iconmoon and run it through ttf2woff, its flawless. 
![cjy62gy](https://cloud.githubusercontent.com/assets/9802268/7723055/c4d2c78a-fee5-11e4-82ea-6f483a1b33be.jpg)
(fonts generated http://kexe.dk/fontTests.zip

**Comment by RobeeeJay** [comment]
Having the same issue with IE as well. :(

**Comment by puzrin** [comment]
Can anyone try to test HHEA lineGap = 0 ? Need to patch this line https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/hhea.js#L14

If this will not help, set OS/2 sTypoLineGap to 0 too: https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/os2.js#L64

**Comment by RobeeeJay** [comment]
@puzrin Sorry for taking so long to get around to this, but I've finally tested setting lineGap to 0 in hhea.js and yes, that fixes the problem! Didn't need to change os2.js (although initially I did and it made no difference on its own).

**Comment by thamagnetix** [comment]
@puzrin @RobeeeJay yup - that fixes the issue.
