### ISSUE TITLE
problem with horizontal alignment

### ISSUE THREAD

**Issue by mstorus** [fontello/svg2ttf#28]
I have an SVG where the left side of the path extends to the left of the canvas. But after converting this SVG to TTF, the left side of the path gets aligned with x=0 on the canvas.
(my use of the term "canvas" might be incorrect, I don't know the proper term)

My desired outcome is that the left side of the glyph will maintain it's position relative to the canvas, rather than getting pushed to the right past x=0. Is there any way to do this?

SVG file:
---
```
<?xml version="1.0" standalone="no"?> 
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg">
<defs>
  <font id="test" horiz-adv-x="905">
    <font-face font-family="test"
      units-per-em="1000" ascent="1150"
      descent="140" />
    <missing-glyph horiz-adv-x="0" />
    <glyph glyph-name="minus"
      unicode="&#xF18B;"
      horiz-adv-x="905" d=" M0 336H907C919 336 929 346 929 359C929 372 919 382 907 382H0C-12 382 -22 372 -22 359C-22 346 -12 336 0 336z" />
  </font>
</defs>
</svg>

```

actual output:
---
![test ttf - test-1-1](https://cloud.githubusercontent.com/assets/1182738/4497567/3d8bfbcc-4a70-11e4-8dff-7a4dfeacdf83.jpg)

desired output:
---
![test - test-1-1](https://cloud.githubusercontent.com/assets/1182738/4497575/48abff20-4a70-11e4-8e0a-935b0192c1e2.jpg)

**Comment by puzrin** [comment]
Closed in flavour of #29. I've posted possible fix to lsb branch for testing.
