### ISSUE TITLE
SVG canvas should be respected - allowing icons to bleed outside of it

### ISSUE THREAD

**Issue by maranomynet** [fontello/svg2ttf#29]
Hi. Thanks for fixing #26 (and indirectly nfroidure/gulp-iconfont#13)

However there's another problem that remains - namely that icons that "bleed" outside their svg canvas are re-framed/normalized based on their vector shape, instead of the canvas.

I've created a small test that illustrates this: http://mar.eplica.is/gulp-iconfont-bleed-tests.zip

As seen below the `.svg` font respects the canvas correctly, and allows the icon-shapes to bleed outside of it, whereas all the other fonts (derived from the `.svg` font via `svg2ff`) don't.

_Chrome:_
![iconfont-chrome](https://cloud.githubusercontent.com/assets/86827/4536710/9835f2d0-4dcc-11e4-8e02-a41ae7ebdab2.png)

_IE11_
![iconfont-ie](https://cloud.githubusercontent.com/assets/86827/4536711/9b260ca0-4dcc-11e4-9d1e-082f19ee786c.png)

**Comment by puzrin** [comment]
Could you test LSB branch https://github.com/fontello/svg2ttf/tree/lsb ?

It seems lsb is font specifix, used to shift images without coordinates change. That's not our case and min/max should be fine.

As soon as someone can confirm that patch is ok, i will do release.

**Comment by puzrin** [comment]
Closing. I've merged fix to master.
