### ISSUE TITLE
Bytes change with each compile

### ISSUE THREAD

**Issue by greypants** [fontello/svg2ttf#33]
Thanks for this great tool! 

I'm appending md5 hashes to my asset filenames so I can cache them infinitely on my server. The hashes are generated based on the file contents. So unchanged files will always generate the same hash.

Unfortunately, the bytes are changing slightly with each compile from an unchanged source svg font. Ideally, running this conversion on the same file should create the exact output each time, but that's not the case.

![image](https://cloud.githubusercontent.com/assets/647549/6382603/fd6582be-bd17-11e4-96b4-3d356d2a6a46.png)

On the left is the first time I generated the file, and the right is the second time. The source was exactly the same.  Any ideas?

**Comment by puzrin** [comment]
That's a timestamp, by specification.

**Comment by greypants** [comment]
That's what I figured. So it's part of the spec then, and dropping it's not an option?

**Comment by puzrin** [comment]
Only as option to override with fixed timestamp, not by default.

**Comment by greypants** [comment]
Thanks. That'd definitely be helpful. Opened a pull request :point_up:
