### ISSUE TITLE
Internet Explorer 11 has a vertical offset with converted fonts

### ISSUE THREAD

**Issue by RobeeeJay** [fontello/svg2ttf#37]
I'm having the same issue with IE11 as thamagnetix in this closed issue here:
https://github.com/fontello/svg2ttf/issues/26#issuecomment-103827980

However after trying just about everything I did find a fix (which is not ideal) which involved opening the font in FontForge and changing two parameters, then saving out the font again in each required format:
https://github.com/FontCustom/fontcustom/issues/197#issuecomment-38599583

I'm not sure what the implications of this would be for other fonts, it doesn't affect our custom icon font in Chrome or Firefox.

**Comment by puzrin** [comment]
@RobeeeJay could you test 2 changes below?

1. Set HHEA lineGap = 0. Need to patch this line https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/hhea.js#L14
2. (only if (1) will not help) Set OS/2 sTypoLineGap to 0 too: https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/os2.js#L64

**Comment by RobeeeJay** [comment]
@puzrin 1) works! \o/

**Comment by puzrin** [comment]
Thanks! That's always an ass pain to test IE :)

Released 3.0.0 with updated lineGap & fsType.

**Comment by RobeeeJay** [comment]
Unfortunately 3.0.0 didn't fix the line gap issue, the setter is never being called because it is not defined until after the default value is being set. :( So the lineGap is still being set as a function of the ascent and descent values. :/

Also, if you do move the getters/setters above the initial settings, an infinite call loop is set up because of a typo in the comparison of the getter:

`this.lineGap` should be `this.int_lineGap`

**Comment by puzrin** [comment]
Should be fixed in master. Will release tomorrow after some chacks.

Thanks for pointing out this mistake!

**Comment by puzrin** [comment]
Released 4.0.0

**Comment by RobeeeJay** [comment]
That's great, thanks for such a quick turnaround! I'll check it later today.

**Comment by yisibl** [comment]
I want to know if lineGap in the hhea table is also set to non-zero, what will happen in IE11?
