### ISSUE TITLE
Missing required table: "post"

### ISSUE THREAD

**Issue by Neema** [fontello/svg2ttf#41]
This is more of a question than it is an issue (for the time being) 
Not sure if it's my particular font, but I ran my font through fontlint and it returned 
"  "Missing required table: "post" " 
Along with all the other glyph related errors (that I caused myself :tada:)

I'm using gulp-svg2ttf, for what its worth, I'm gonna try creating another font and running that through fontlint as well - but is anyone else having the same issue?

**Comment by puzrin** [comment]
No idea. I never user programs you mention. It worth to create minimal demo, if you are sure problem is related to this project.

**Comment by Neema** [comment]
Is there a set of SVGs that you use to test and verify that svg2ttf works? If there is, could I possibly get my hands on that set (as well as the expected output, the ttf file)

**Comment by puzrin** [comment]
It sertaintly works. You can check dependemt projects in npm or take svg font generated by fontello.
