### ISSUE TITLE
Please add proper support for font.weightClass

### ISSUE THREAD

**Issue by lunaroja** [fontello/svg2ttf#43]
https://github.com/fontello/svg2ttf/blob/56b97c98de9d290707545068f703bdb8a8f438c8/index.js#L42
// need to correctly convert text values, use default (400) until compleete
//font.weightClass = svgFont.weightClass;

`svgicons2svgfont` has added support for `fontWeight`, but this does not carry over to the TTF files.
https://github.com/nfroidure/svgicons2svgfont/commit/a33ae62f31fec87eef9ecde3b874ff7ea37dfcf6

**Comment by puzrin** [comment]
PR welcome. I don't know exact rules, because weight can be digital and named.

**Comment by abrahamvelazquez** [comment]
I found this. https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping

**Comment by puzrin** [comment]
https://github.com/fontello/svg2ttf/commit/6b422340af615bc4c0f7d742330d8785dfd83f7f
