### ISSUE TITLE
SVG with overlap gets rendered transparent

### ISSUE THREAD

**Issue by michael-jerred** [fontello/svg2ttf#44]
When I convert an svg with overlapping regions, the regions that have an overlap become transparent in the font.

Example:

    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 300 300" enable-background="new 0 0 300 300" xml:space="preserve">
    <g>
        <circle fill="#231F20" cx="149.5" cy="101.1" r="47.6"/>
        <polygon fill="#231F20" points="161.4,223.6 138.6,246.5 138.6,140.6 161.4,140.6     "/>
    </g>
    </svg>

**Comment by puzrin** [comment]
You have to correctly prepare your source first https://github.com/fontello/fontello/wiki/How-to-use-custom-images#importing-svg-images.
