### ISSUE TITLE
Consider set fsType = 0

### ISSUE THREAD

**Issue by puzrin** [fontello/svg2ttf#45]
https://github.com/fontello/fontello/issues/436#issuecomment-167916066

**Comment by diegoflorez** [comment]
@puzrin 
Setting fsType = 0, is it setting BitMask = 0x0001?
In order to get BitMask = 0x0000, should fsType be unset?

https://www.microsoft.com/typography/otspec/os2.htm#fst

**Comment by puzrin** [comment]
> Setting fsType = 0, is it setting BitMask = 0x0001?

Yes.

**Comment by puzrin** [comment]
Ups, no :)

fsType = 0 means BitMask = 0x0000
