### ISSUE TITLE
Poor-quality converted glyphs

### ISSUE THREAD

**Issue by gmckeown** [fontello/svg2ttf#52]
I've been digging into an issue with the quality of icons used in the [Seti UI](https://github.com/jesseweed/seti-ui) project. It seems that when the [SVG font](https://github.com/jesseweed/seti-ui/blob/master/styles/_fonts/seti/seti.svg) is converted to TTF, the quality of the glyphs is badly affected. This seems most obvious with curves, but doesn't seem limited to them (e.g. the "M" in "ASM" below).

For example, here are some original SVG font glyphs:
![svgfont_birdfont](https://cloud.githubusercontent.com/assets/22765233/24245859/7fee4ed4-0fbc-11e7-9470-68f288baf0f1.png)

And here's what they look like after conversion to [TTF](https://github.com/jesseweed/seti-ui/blob/master/styles/_fonts/seti/seti.ttf):
![svgfont_ttf_birdfont](https://cloud.githubusercontent.com/assets/22765233/24245872/8b71b732-0fbc-11e7-9758-c8b5cb6e592f.png)

Command-line used:
```
svg2ttf seti.svg seti.ttf
```
Could this be related to issue https://github.com/fontello/svg2ttf/issues/25 ?

Original issue against Seti UI: https://github.com/jesseweed/seti-ui/issues/401

**Comment by puzrin** [comment]
Looks like initial dimensions are very low and suffer from rounding. I'd suggest 1000px and more.

- Could you show your SVG font src? If possible - leave only couple of simple bad images
- Drop it to fontello and check if generated font is ok or not (it normalizes size)

**Comment by gmckeown** [comment]
Full font sources (both the individual SVG images and the generated SVG font) are linked in the original issue above.

Here's a smaller subset. This is created using svgicons2svgfont. They look OK in Fontello.

[svgtest_sample.zip](https://github.com/fontello/svg2ttf/files/864576/svgtest_sample.zip)

**Comment by puzrin** [comment]
`<font-face font-family="svgtest" units-per-em="32" ascent="32" descent="0" />`

Problem is in your SVG prepare process. Dimentions should be 1000 and more. I think your tools just take  original images as is and don't care about upscale. For example, if you import this font to fontello, result will be good.

**Comment by puzrin** [comment]
If you decide write manual scaler, that will help https://github.com/fontello/svgpath.

**Comment by gmckeown** [comment]
Thank you for your quick and helpful response! I have tested with larger dimensions in the prep process (it uses gulp-iconfont) and it seems to do the job. Have submitted a [pull request](https://github.com/jesseweed/seti-ui/pull/405) to the Seti UI project.
