### ISSUE TITLE
Font symbols look not sharp

### ISSUE THREAD

**Issue by AGavrashenko** [fontello/svg2ttf#65]
Hello.
I'm using svg2ttf for generating ttf font for processing to other formats like eot, woff, etc.
I've noticed that icons in ttf are have crashed edges in IE and Firefox(Windows).
<img width="138" alt="screen shot 2018-03-15 at 12 01 23 pm" src="https://user-images.githubusercontent.com/17312551/37456688-a94f4468-2848-11e8-8051-3dde40c2b395.png">
Currently, I use this config:
```    
{
    fontHeight: 1024,
    ascent: 896,
    descent: 128
}
```
But I've tried different variants and received the same result.

Also, I've tried to convert my svg font via other online tools.
The result I received (svg2ttf from the left):
<img width="300" alt="screen shot 2018-03-15 at 12 01 37 pm" src="https://user-images.githubusercontent.com/17312551/37456689-a981ad72-2848-11e8-8658-fc614f32e9c7.png">
All screenshots was made in IE.
As you can see, the font looks much better.
So, is this an issue of svg2ttf?

**Comment by puzrin** [comment]
Did you tried to apply `ttfautohint` after svg2ttf?

https://github.com/fontello/fontello/blob/97d3bdb0d45a9cb165bf9218f9c510c0fa3120c8/internal/fontello/font_build/_lib/worker.js#L118-L136

**Comment by AGavrashenko** [comment]
@puzrin no, I didn't.

**Comment by puzrin** [comment]
I guess, that's not issue of svg2ttf then.
