### ISSUE TITLE
Not able to set fsType via options

### ISSUE THREAD

**Issue by tommyka** [fontello/svg2ttf#73]
fsType is now hardcoded to 8. This triggers a error in IE11 when trying to use the fonts.
If the default is set to 0 or make it possible to overwrite via options, would fix the ie issue

**Comment by puzrin** [comment]
You report is invalid, because default fsType is 0.

Also source code contains clear comment about that https://github.com/fontello/svg2ttf/blob/master/lib/sfnt.js#L19m with reference to issue and details https://github.com/fontello/svg2ttf/issues/45.
