### ISSUE TITLE
have to use command "node --max-old-space-size=8192 svg2ttf.js"

### ISSUE THREAD

**Issue by creatxrgithub** [fontello/svg2ttf#91]
have to use command "node --max-old-space-size=8192 svg2ttf.js"

maybe it could be optimized.

thanks

**Comment by puzrin** [comment]
I don't understand what are you talking about. Could you explain?

**Comment by creatxrgithub** [comment]
other message:

(node:11628) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by creatxrgithub** [comment]
i have a large svg file (about 65535 glyphs), so i have to use option "--max-old-space-size=8192"

i think that maybe svg2ttf could be better.

@puzrin

**Comment by puzrin** [comment]
IMO that's a very specific case, i'm not interested spent time for such optimization. But if someone suggest PR, it will be accepted.

**Comment by puzrin** [comment]
Close as "wontfix"
