### ISSUE TITLE
Impossible to convert this SVG into TTF

### ISSUE THREAD

**Issue by arochettesteinberg** [fontello/svg2ttf#97]
Hi

I've been trying to convert a few simple SVGs exported from Photoshop into a TTF using svg2ttf... unsuccessfully.

No matter how simple the SVG is, I always run into the following error that my SVG file isn't a font. I'm a bit confused. I thought the aim of this tool was precisely to convert SVG glyphs into TTF?

`Error: Can't find <font> tag. Make sure you SVG file is font, not image.`

I've attached one SVG of mine as an example.

[folder.zip](https://github.com/fontello/svg2ttf/files/4599538/folder.zip)

Thank you very much for your help!

**Comment by puzrin** [comment]
This package is not for SVG icons, it's for SVG fonts. You need something like https://github.com/nfroidure/svgicons2svgfont

**Comment by arochettesteinberg** [comment]
"And then there was light!" Thanks!
